version: '3'

services:
    sql-server:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password1234
            - MSSQL_PID=Developer
        ports:
            - "1433:1433"
        container_name: sql-server